### ISSUE TITLE
Crane fails to index project

### ISSUE THREAD

**Issue by Novynn** [HvyIndustries/crane#137]
It simply freezes up at 65.3% (6261/9586 for me). 

There are no useful messages in the Crane Console output (debugMode: true of course). When I try to reindex it gets stuck on "preparing" and never starts up again.

![image](https://cloud.githubusercontent.com/assets/1468831/17610554/34e8d8ce-6093-11e6-891c-fd224be2f522.png)

Using Crane 0.2.0.

I wish I had a more useful report, hopefully we'll get some more debug output in the near future.

**Comment by zealitude** [comment]
Same situation, my indexing is freeze up at 7.2%(596 of 8313) everytime

**Comment by abdulrauf99** [comment]
I'm also facing same situation freeze at 16.3%

**Comment by alex-pex** [comment]
Stuck at (69 of 11511 / 0.6%)

**Comment by John0King** [comment]
This will happen when vs code run  `git fetch` ` git pull`.

**Comment by Novynn** [comment]
@John0King even with Git disabled in VSCode (via `"git.enabled": false`) the issue still occurs for me.

**Comment by styler2go** [comment]
very same problem with bigger project. stuch at 459/1067 (43%). after restarting it stucks on different positions.

**Comment by nevadascout** [comment]
Hey guys, thanks for reporting this. It's likely caused by some kind of parser error, so we need to try to nail down which code in which file is breaking the parser.

You should be able to use the debug console to figure out which file it is breaking on, then if you could share the code of that file with us (or privately with just me) we should be able to figure out what the issue is.

Longer term, we need to add more logic to handle errors better, but there was a bug in the parser itself which I believe was completely crashing the "server" thread, instead of throwing an exception that could be caught.

**Comment by Novynn** [comment]
Correct me if I'm wrong, but the debug output seems to only report successful file parsing, and therefore shows no indication of which file it's failing on.

**Comment by alex-pex** [comment]
@nevadascout Nothing special, Crane stuck at (49 of 11511 / 0.4%)

No error on debug console : [INFO] Parsed file 49 of 11511 : /home/alexandre/workspace/sf2_wingu/src/Wingu/ExamBundle/WinguExamBundle.php

The file is nearly empty : 

```php
namespace Wingu\ExamBundle;

use Symfony\Component\HttpKernel\Bundle\Bundle;

class WinguExamBundle extends Bundle
{
}
```

**Comment by chendong152** [comment]
Same situation, stopped at 4648/13204(35.2%)
my situation:
    3 laravel projects in the parent folder and I open the parent folder

Then I opened one of them only, it works well.

**Comment by naduvko** [comment]
I have old projects where yii framework is outside workspace, and there is no way VCode to access the framework. On all of these indexing freezes.

**Comment by ritoscue** [comment]
My index process stops  always in the same point "PHP files (256 of 541/ 47.3%)".
Debug Console doesn't show anything.
I don't have idea what is wrong.

**Comment by Novynn** [comment]
As of v0.2.1 my issue has been fixed! I urge the commenters in this thread to retry Crane.

**Comment by Novynn** [comment]
Hmm, now it seems stuck on "Packing tree file"

**Comment by smbkr** [comment]
Still happening for me - seems to happen on random files, as it's different each time. There's around 3000 files in this project, and it seems to hang around the 28% mark (approx 850 files in). There doesn't seem to be a pattern to what it's failing on - some of the files are longer and more complex, whereas one was literally one require statement and a comment.

The source is closed so I can't share it for debugging/analysis.

There's no abnormal CPU/memory utilisation when it stops. There's one active VSCode instance that's stuck right now as I type this, but it's only using ~1% CPU and 14 MB of RAM.

Platform is Windows 10 x64.
VS Code version 1.6.0 commit c9aa55

**Comment by nevadascout** [comment]
Hi @smbkr, we're aware of this and it should be fixed with the new version of the php-parser that is being worked on in an upcoming release.

**Comment by smbkr** [comment]
Cheers @nevadascout - any ETA for the release?

**Comment by nevadascout** [comment]
Not 100% sure, hopefully within a few weeks.

**Comment by michalhudecek** [comment]
This would be a great quick workaround for this issue: https://github.com/HvyIndustries/crane/issues/77

**Comment by unional** [comment]
Getting stuck too. on tcpdf

**Comment by nevadascout** [comment]
This should be fixed with the update of php-parser to 2.0.0

**Comment by nevadascout** [comment]
Fixed in v0.3.0
